version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    deploy:
      replicas: 1
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3

  kafka:
    image: wurstmeister/kafka
    ports:
        - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "samantha:1:1,samantha-response:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
    deploy:
      replicas: 1
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3C
