# userID is used to identify the client which sends message the NLP provider.
# It must be a version 4 UUID.
# Generate a new UUID here: https://www.uuidgenerator.net/version4
userID: d56b1e74-b6ca-4536-a114-cf80523da0ef

# IBM Watson credentials.
label: "Watson"
url: "https://gateway-lon.watsonplatform.net/assistant/api"
version: "2018-09-20"
token: "x3eA-ZDYithX38WYIojAkXHwJ0m5-Xgk3u7exjIa3kjP"
assistantID: "5675269e-7d69-4e1c-933d-edf44ceae522"
