# userID is used to identify the client which sends message the NLP provider.
# It must be a version 4 UUID.
# Generate a new UUID here: https://www.uuidgenerator.net/version4
userID: 

# IBM Watson credentials.
label: ""
url: ""
version: ""
token: ""
assistantID: ""
